from pandas import DataFrame


def clean_automatic_events(df: DataFrame) -> DataFrame:
    """
    Remove unnecessary data. Here are listed logs that usually do not involve any user actions, rather are
    automatically generated by the system.
    """

    # automatically generated events that do not involve student actions
    grd_itm_ctd = list((df.loc[df['Role'] == 'Student'].loc[df['Event_name'] == 'Grade item created']).index)
    grd_itm_upd = list((df.loc[df['Role'] == 'Student'].loc[df['Event_name'] == 'Grade item updated']).index)
    user_graded = list((df.loc[df['Role'] == 'Student'].loc[df['Event_name'] == 'User graded']).index)
    notification = list((df.loc[df['Event_name'] == 'Notification sent']).index)

    to_remove = grd_itm_ctd + grd_itm_upd + user_graded + notification
    df.drop(to_remove, axis=0, inplace=True)
    df = df.reset_index(drop=True)

    return df


def clean_specific_events(df: DataFrame) -> DataFrame:
    """
    Remove unnecessary data specific to your dataset.
    Please be aware that if you are performing any temporal analysis these activities must be removed after
    duration calculation. The function is customisable according to your needs.

    """

    # events not informative for temporal analysis
    activity_completion = list((df.loc[df['Event_name'] == 'Course activity completion updated']).index)
    # actions performed by users with the guest role
    guest = list((df.loc[df['Role'] == 'Guest']).index)
    # actions performed on deleted modules, activities, or users.
    deleted = list((df.loc[df['Status'] == 'DELETED']).index)

    to_remove = activity_completion + guest + deleted
    df.drop(to_remove, axis=0, inplace=True)
    df = df.reset_index(drop=True)

    return df
